### ISSUE TITLE
Big problem with generated references longer then 9 chars

### ISSUE THREAD

**Issue by gett-thijssimonis** [blauwfruit/PrestaShop-Order-Reference#8]
PrestaShop reference column on support 9 chars, saving more than 9 chars will give problems with accepting the payment request. Not only payments will give problems it also create duplicates at a time.

I created a PR #7 to hotfix this issue with `substr` it to 9 chars, but this is not the preferred solution. Maybe consider one of the following solution to fix this properly:
* Warn the BO user about this issue
* Alter the reference  column (multiple places) to more chars  (give problems with PS updates)
* Just leave the reference as it is and save custom reference in a extra column (give problems with PS updates) and overwrite reference with hooks...
* ^ solution as above but save it in a custom table with reference to the PrestaShop reference

**Comment by muyncky** [comment]
Hi Thijs,

That is a bad issue, good catch.

I think your first suggestion to give a warning is a good one. The other option will create a new feature which in turn can give more issues. I prefer to keep the module simple. I hope you agree with that.

Warning the merchant in the BO on saving is not always possible (since the length can vary). An explanation of the restrictions is good, and whenever a long reference is detected on saving the settings, it should give an error.

Let me know what you think about this!
